"""phase2_initial_schema

Revision ID: f0f5111533ad
Revises: 
Create Date: 2026-10-02 09:08:58.876756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0f5111533ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('kernel_version', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('total_memory_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_disk_bytes', sa.BigInteger(), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('healthy', 'degraded', 'critical', 'offline')", name='ck_hosts_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_hosts_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_status'), ['status'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('systemd_unit', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'failed', 'degraded')", name='ck_services_status'),
    sa.CheckConstraint('port IS NULL OR (port > 0 AND port <= 65535)', name='ck_services_port'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name', name='uq_services_host_name')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_status'), ['status'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployed_by', sa.String(length=100), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('started', 'completed', 'failed', 'rolled_back')", name='ck_deployments_status'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_deployed_at'), ['deployed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_deployments_service_deployed_at', ['service_id', 'deployed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("level IN ('DEBUG', 'INFO', 'WARN', 'WARNING', 'ERROR', 'CRITICAL', 'FATAL')", name='ck_logs_level'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_logs_fingerprint_ts', ['fingerprint', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_logs_host_level_ts', ['host_id', 'level', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_service_id'), ['service_id'], unique=False)
        batch_op.create_index('ix_logs_service_level_ts', ['service_id', 'level', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_metrics_host_name_ts', ['host_id', 'metric_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_service_id'), ['service_id'], unique=False)
        batch_op.create_index('ix_metrics_service_name_ts', ['service_id', 'metric_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('service_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_service_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("criticality IN ('critical', 'non_critical', 'optional')", name='ck_service_dependencies_criticality'),
    sa.CheckConstraint("dependency_type IN ('synchronous', 'asynchronous', 'database', 'internal_call')", name='ck_service_dependencies_type'),
    sa.CheckConstraint('service_id != depends_on_service_id', name='ck_service_dependencies_no_self_loop'),
    sa.ForeignKeyConstraint(['depends_on_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'depends_on_service_id', name='uq_service_dependencies_edge')
    )
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_dependencies_depends_on_service_id'), ['depends_on_service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_dependencies_service_id'), ['service_id'], unique=False)

    op.create_table('config_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('config_file_path', sa.String(length=500), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("change_type IN ('modify', 'add', 'delete', 'env_var_update')", name='ck_config_changes_type'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_changes_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_changes_config_file_path'), ['config_file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_changes_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index('ix_config_changes_host_changed_at', ['host_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_changes_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_config_changes_service_changed_at', ['service_id', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_changes_service_id'), ['service_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('correlated_deployment_id', sa.Uuid(), nullable=True),
    sa.Column('correlated_config_change_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('critical', 'high', 'medium', 'low')", name='ck_incidents_severity'),
    sa.CheckConstraint("status IN ('open', 'investigating', 'mitigated', 'resolved', 'closed')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['correlated_config_change_id'], ['config_changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['correlated_deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_correlated_config_change_id'), ['correlated_config_change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_correlated_deployment_id'), ['correlated_deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index('ix_incidents_host_detected_at', ['host_id', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index('ix_incidents_status_severity', ['status', 'severity'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_incident_events_incident_ts', ['incident_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('remediations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending_approval', 'approved', 'rejected', 'executed', 'failed')", name='ck_remediations_status'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remediations_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_events_action_ts', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor'), ['actor'], unique=False)
        batch_op.create_index('ix_audit_events_actor_ts', ['actor', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_remediation_id'), ['remediation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_remediation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index('ix_audit_events_actor_ts')
        batch_op.drop_index(batch_op.f('ix_audit_events_actor'))
        batch_op.drop_index('ix_audit_events_action_ts')
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediations_status'))
        batch_op.drop_index(batch_op.f('ix_remediations_incident_id'))

    op.drop_table('remediations')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_timestamp'))
        batch_op.drop_index('ix_incident_events_incident_ts')
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_events_event_type'))

    op.drop_table('incident_events')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_status_severity')
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_service_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_host_id'))
        batch_op.drop_index('ix_incidents_host_detected_at')
        batch_op.drop_index(batch_op.f('ix_incidents_detected_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_correlated_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_correlated_config_change_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('config_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_changes_service_id'))
        batch_op.drop_index('ix_config_changes_service_changed_at')
        batch_op.drop_index(batch_op.f('ix_config_changes_host_id'))
        batch_op.drop_index('ix_config_changes_host_changed_at')
        batch_op.drop_index(batch_op.f('ix_config_changes_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_config_changes_config_file_path'))
        batch_op.drop_index(batch_op.f('ix_config_changes_changed_at'))

    op.drop_table('config_changes')
    with op.batch_alter_table('service_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_dependencies_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_dependencies_depends_on_service_id'))

    op.drop_table('service_dependencies')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_timestamp'))
        batch_op.drop_index('ix_metrics_service_name_ts')
        batch_op.drop_index(batch_op.f('ix_metrics_service_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_metric_name'))
        batch_op.drop_index('ix_metrics_host_name_ts')
        batch_op.drop_index(batch_op.f('ix_metrics_host_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_timestamp'))
        batch_op.drop_index('ix_logs_service_level_ts')
        batch_op.drop_index(batch_op.f('ix_logs_service_id'))
        batch_op.drop_index(batch_op.f('ix_logs_level'))
        batch_op.drop_index('ix_logs_host_level_ts')
        batch_op.drop_index(batch_op.f('ix_logs_host_id'))
        batch_op.drop_index('ix_logs_fingerprint_ts')
        batch_op.drop_index(batch_op.f('ix_logs_fingerprint'))

    op.drop_table('logs')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_service_id'))
        batch_op.drop_index('ix_deployments_service_deployed_at')
        batch_op.drop_index(batch_op.f('ix_deployments_host_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_deployed_at'))

    op.drop_table('deployments')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_status'))
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.drop_index(batch_op.f('ix_services_host_id'))

    op.drop_table('services')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_status'))
        batch_op.drop_index(batch_op.f('ix_hosts_last_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_hosts_hostname'))

    op.drop_table('hosts')
    # ### end Alembic commands ###
